doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/migrations'

when@test:
    doctrine_migrations:
        migrations_paths:
            'DoctrineMigrations': '%kernel.project_dir%/migrations'
