security:
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: /post-login
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/market, roles: PUBLIC_ACCESS }
        - { path: ^/cart, roles: ROLE_CUSTOMER }
        - { path: ^/my-orders, roles: ROLE_CUSTOMER }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/farm, roles: ROLE_FARMER }
        - { path: ^/products, roles: ROLE_FARMER }
        - { path: ^/orders, roles: ROLE_FARMER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/post-login, roles: ROLE_USER }
        - { path: ^/$, roles: ROLE_FARMER }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_FARMER, ROLE_CUSTOMER]
