parameters:
    recaptcha_site_key: '%env(RECAPTCHA_SITE_KEY)%'
    recaptcha_secret_key: '%env(RECAPTCHA_SECRET_KEY)%'
    google_client_id: '%env(GOOGLE_CLIENT_ID)%'
    google_client_secret: '%env(GOOGLE_CLIENT_SECRET)%'
    google_redirect_uri: '%env(GOOGLE_REDIRECT_URI)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\AiService:
        arguments:
            $huggingFaceApiToken: '%env(default::HUGGINGFACE_API_TOKEN)%'

    App\Service\SalesInsightsService:
        arguments:
            $huggingFaceApiToken: '%env(default::HUGGINGFACE_API_TOKEN)%'

    App\Service\CloudinaryService:
        arguments:
            $cloudName: '%env(CLOUDINARY_CLOUD_NAME)%'
            $apiKey: '%env(CLOUDINARY_API_KEY)%'
            $apiSecret: '%env(CLOUDINARY_API_SECRET)%'
            $localUploadDir: '%products_upload_dir%'

    App\Service\EmailService:
        arguments:
            $fromEmail: '%env(MAILER_FROM)%'

    App\Service\CurrencyConverterService:
        arguments:
            $apiUrl: '%env(CURRENCY_API_URL)%'

    App\Service\StripeCheckoutService:
        arguments:
            $secretKey: '%env(default::STRIPE_SECRET_KEY)%'

    App\Service\TemporaryShippingStorage:
        arguments:
            $cache: '@cache.app'
